swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10011
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json

paths:
  /login:
    # binds a127 app logic to a route
    x-swagger-router-controller: loginController
    post:
      description: Returns JWT token
      # used as the method name of the controller
      operationId: login
      parameters:
        - name: body
          in: body
          description: Login Credectials
          required: true
          schema:
            $ref: "#/definitions/LoginCredentials"

      responses:
        "200":
          description: Login Success
          schema:
            $ref: "#/definitions/LoginSuccess"
            
        "401":
          description: Login Failure
          schema:
            $ref: "#/definitions/LoginFailure"

        default:
          description: Uncaught Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /register:
    x-swagger-router-controller: userController
    post:
      description: Register a new User
      operationId: registerUser
      parameters:
        - in: body
          name: body
          description: User Registration Data
          required: true
          schema:
            $ref: "#/definitions/UserRegistration"

      responses:
        "200":
          description: Registration Success
          schema:
            $ref: "#/definitions/LoginSuccess"
            
        "401":
          description: Registration is not allowed
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  UserRegistration:
    required:
      - username
      - password
      - passwordConfirm
      - email
    properties:
      username:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string

  LoginCredentials:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
        
  LoginSuccess:
    required:
      - token
    properties:
      token:
        type: string
      username:
        type: string
      firstName:
        type: string
        
  LoginFailure:
    required:
      - message
    properties:
      message:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
      detail:
        type: string
